CL_coeff: 0.001
Cos_coeff: 0.7
KL_coeff: 0.1
batch_norm: 1
clip_grads: false
codebook_dim: 256
codebook_init: normal
codebook_slots: 256
compress: 2
cos_reset: 0
dec_hidden_dim: 16
decay: true
enc_hidden_dim: 16
gs_temp: 0.667
input_feat_dim: 2
layer: 0
lr: 0.0004
num_res_blocks: 0
output_dir: CodeCos2R
reset_choice: 0
